// social-media-dashboard-svelte/src/lib/components/ui/Text.svelte
<!--
@component
- Renders a reusable text component
- Usage:
```HTML
    <Text class="text-teal-500">Hello World!</Text>
```
-->
<script lang="ts">
    import type { Snippet } from 'svelte'
    import { classMerger } from '@lib/utils/classMerger'

    interface TextProps {
        children?: Snippet
        className?: string
    }

    let { children, className }: TextProps = $props()
</script>

<p class={classMerger(
    'text-neutral-blue-dark-grayish font-semibold dark:text-neutral-blue-grayish-desaturated',
    className
)}>
    {@render children?.()}
</p>

// social-media-dashboard-react/src/components/ui/Text.tsx
import type { ReactNode } from 'react'
import { classMerger } from '@utils/classMerger'

interface TextProps {
    children?: ReactNode
    className?: string
}

/**
 * Renders a reusable paragraph component
 * that can be personalized with different styles.
 * 
 * @example
 * <Text className="text-lg">Hello, World!</Text>
 */
export default function Text({ children, className }: TextProps) {
    return (
        <p className={classMerger(
            'text-neutral-blue-dark-grayish font-semibold dark:text-neutral-blue-grayish-desaturated', 
            className
        )}>
            {children}
        </p>
    )
}
