// social-media-dashboard-react/src/components/total-card/VariationValue.tsx
import upIcon from '@assets/icon-up.svg'
import downIcon from '@assets/icon-down.svg'
import Image from '@components/ui/Image'
import Text from '@components/ui/Text'

interface VariationValueProps {
    increased: boolean
    type: string
    today_change: number
}

/**
 * Renders the components that shows the 
 * variation of a metric per component card.
 * 
 * @example
 * import VariationValue from '@/components/total-card/VariationValue'
 * 
 * function TotalCard({ name, age, purchases }: { name: string, age: number, purchases: number }) {
 *  return (
 *      <VariationValue
 *          increased={true}
 *          type=" Today"
 *          today_change={313} 
 *      />
 *  )
 * }
 */
export default function VariationValue({ increased, type, today_change }: VariationValueProps) {
    return (
        <article className="flex items-center gap-1">
            <Image
                src={increased ? upIcon : downIcon}
                alt={increased ? 'Increased' : 'Decreased'}
                className="w-2 h-1"
            />
            <Text 
                className={increased 
                    ? "text-primary-turquoise-light dark:text-primary-turquoise-light" 
                    : "text-primary-red dark:text-primary-red"
                }
            >
                {today_change + type}
            </Text>
        </article>
    )
}

// social-media-dashboard-svelte/src/lib/components/total-card/VariationValue.svelte
<!--
@component
- Renders a component that shows the
variation of a metric per component card
- Usage:
```HTML
    <VariationValue increased={false} type="%" today_change={66} />
```
-->
<script lang="ts">
    import Image from '@lib/components/ui/Image.svelte'
    import Text from '@lib/components/ui/Text.svelte'
    import downIcon from '@assets/icon-down.svg'
    import upIcon from '@assets/icon-up.svg'

    interface VariationValueProps {
        increased: boolean
        type: string
        today_change: number
    }

    let { increased, type, today_change }: VariationValueProps = $props()
</script>

<article class="flex items-center gap-1">
    <Image 
        src={increased ? upIcon : downIcon}
        alt={increased ? 'Increased' : 'Decreased'}
        class="w-2 h-1"
    />
    <Text
        className={increased
            ? 'text-primary-turquoise-light dark:text-primary-turquoise-light'
            : 'text-primary-red dark:text-primary-red'
        }
    >
        {today_change + type}
    </Text>
</article>
