// social-media-dashboard-react/src/components/ui/Image.tsx
import type { ImgHTMLAttributes } from 'react'
import { classMerger } from '@utils/classMerger'

/**
 * Renders a reusable and customizable image component
 * 
 * @example
 * import Image from '@/components/ui/Image'
 * 
 * function Avatar({ src, alt }) {
 *     return (
 *         <Image src={src} alt={alt} className="w-12 h-12 rounded-full" />
 *     )
 * }
 */
export default function Image({ src, alt, className, ...props }: ImgHTMLAttributes<HTMLImageElement>) {
    return (
        <img 
            src={src} 
            alt={alt}
            className={classMerger(className)}
            {...props}
        />
    )
}

// social-media-dashboard-svelte/src/lib/components/ui/Image.svelte
<!--
@component
- Renders a reusable image tag
- Usage:
  ```HTML
    <Image 
        src="https://random.image.com" 
        alt="Random Image" 
        class="size-10" 
    />
  ```
-->
<script lang="ts">
    import type { HTMLImgAttributes } from "svelte/elements"
    import { classMerger } from '@lib/utils/classMerger'

    let { src, alt, class: className, ...props }:HTMLImgAttributes = $props()
</script>

<img 
    {src} 
    {alt}
    class={classMerger(className)}
    {...props}
>
